version: '3'
services:
  mongo:
    image: mongo:7-jammy
    volumes:
      -  ./mongodb-data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    #user: admin senha: pass
    image: mongo-express:1.0-20-alpine3.19
    links:
      - mongo
    container_name: "mongo-express"
    ports:
      - 8099:8081