app:
  myport: ${PORT:0} # Usando 8083 como valor padrão se PORT não estiver definido

server:
  port: ${app.myport} # Definindo a porta do servidor a partir de app.myport


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: pedido-service
