
app:
  myport: ${PORT:0}
spring:
  application:
    name: imposto-service
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}